apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "flow4xflow-design"
  labels:
    app: "flow4xflow-design"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "flow4xflow-design"
  serviceName: "flow4xflow-design"
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: "flow4xflow-design"
    spec:
      containers:
      - name: "flow4xflow-design"
        image: azuredemocr01.azurecr.io/engage/flowabledesign
        resources: 
          requests:
            memory: "3Gi"
            cpu: "100m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        ports:
        - containerPort: 8080
        env:
        - name: MAX_HEAP
          value: "4096m"
        - name: MIN_HEAP
          value: "4096m"
        - name: CTX_ROOT
          value: "flowable-design"
        - name: ING_HOST
          value: "http://engage-poc-dev-mgmtvm.eastus2.cloudapp.azure.com:443"
        - name: "APPLICATION_ROLE"
          value: "jobmanager"
        - name: "FLOW_CONTROL_CTX_ROOT"
          value: "flowable-control"
        - name: "FLOW_WORK_CTX_ROOT"
          value: "flowable-work"
        - name: "FLOW_DESIGN_CTX_ROOT"
          value: "flowable-design"
        - name: "JAVA_OPTS"
          value: " "
        - name: "TZ"
          value: "US/Eastern"
        - name: "DB_TYPE"
          value: "sqlserver"
        - name: "DB_VERSION"
          value: ""
        - name: "SESSION_TIMEOUT"
          value: "600"
        - name: "MAX_SESSION"
          value: ""
        - name: "REDIS_HOST_PORT"
          value: "release-name-redis-ha.redis:6379"
        - name: "ELASTIC_HOST_PORT"
          value: "10.244.0.182:9200"
        - name: "LOG_LEVEL"
          value: "INFO"
        - name: "VLSOUT_LOG_LEVEL"
          value: "SEVERE"
        - name: "CUSTOMIZATIONFOLDER"
          value: "Custom"
        - name: "DEPLOYEDTOPOLOGY"
          value: "LAN"
        - name: "PRODUCTTABTITLE"
          value: "CGIAdvantageFlow"
        - name: "ENV_NAME"
          value: "flow-2022.FS3.2-SHK.0"
        - name: "JOB_THREAD_COUNT"
          value: "4"
        - name: "SECRET_MANAGEMENT"
          value: "k8s"
        - name: "ADV_USER"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-application-user"
              key: "ADV_USER"
        - name: "ADV_PASS"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-application-user"
              key: "ADV_PASS"
        - name: "SUBVALUSER"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "SUBVALUSER"
        - name: "SUBVALPASSWORD"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "SUBVALPASSWORD"
        - name: "FLOW_LOGIN"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "FLOW_LOGIN"
        - name: "FLOW_DATABASE"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "FLOW_DATABASE"
        - name: "FLOW_SCHEMA"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "FLOW_SCHEMA"
        - name: "FLOW_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "FLOW_PASSWORD"
        - name: "FLOW_HOST"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "FLOW_HOST"
        - name: "FLOW_PORT"
          valueFrom:
            secretKeyRef:
              name: "flow4xflow-design-db-secret"
              key: "FLOW_PORT"
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: acrtoaks-secret-new1
      securityContext:
        runAsGroup: 1004
        runAsUser: 185
      
