FROM lin-adv40-harbor.cgiadv.com/temp/flowdesign:4.4A.18
COPY /application.properties /apps/CGIADV/flowable/tomcat/lib/application.properties
#EXPOSE 9081
#COPY activemq /apps/CGIADV/flowable/activemq
#COPY elasticsearch /apps/CGIADV/flowable/elasticsearch

