apiVersion: v1
kind: Service
metadata:
  name: flowable-control
  labels:
    app: flowable-control
spec:
  ports:
  - name: http
    port: 8092
    targetPort: 8092
  selector:
    app: flowable-control
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowable-control
spec:
  selector:
    matchLabels:
      app: flowable-control
  template:
    metadata:
      labels:
        app: flowable-control
    spec:
      containers:
      - env:
        - name: flowable.common.app.idm-admin.user
          value: admin
        - name: flowable.common.app.idm-admin.password
          value: test 
        - name: flowable.control.app.cluster-config.server-address
          value: http://flowable-work 
        - name: flowable.control.app.cluster-config.port
          value: "8080" 
        - name: flowable.control.app.cluster-config.context-root
          value: /
        - name: flowable.control.app.cluster-config.password
          value: test 
        - name: server.servlet.context-path
          value: /
        - name: spring.datasource.driver-class-name
          value: org.postgresql.Driver
        - name: spring.datasource.url
          value: jdbc:postgresql://engage-poc-dev-pg3.postgres.database.azure.com:5432/flowable
        - name: spring.datasource.username 
          value: postgres@engage-poc-dev-pg3
        - name: spring.datasource.password
          value: engage123!          
        image: artifacts.flowable.com/flowable/flowable-control:latest
        name: flowable-control
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8092
      imagePullSecrets:
        - name: quickstart-flowable-regcred
     

      

     
      
      
   
     
     
     
     
   


