FROM lin-adv40-harbor.cgiadv.com/temp/flowwork:4.4A.18
COPY /workapplication.properties /apps/CGIADV/flowable/tomcat/lib/application.properties
#COPY activemq /apps/CGIADV/flowable/activemq
#COPY elasticsearch /apps/CGIADV/flowable/elasticsearch
#E#XPOSE 9081


